# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NERtcSample-GroupVideoCall-iOS-Objective-C' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'NERtcSDK', '3.6.0'

end
