# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NERtcSample-GroupVideoCall-iOS-Objective-C' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'NERtcSDK', '~> 3.5.2'

  # Pods for NERtcSample-GroupVideoCall-iOS-Objective-C

  target 'NERtcSample-GroupVideoCall-iOS-Objective-CTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
