
export default class CommonConstants {
  /**
   * The settings page url.
   */
  static readonly SETTINGS_URL: string = 'pages/Settings';

  /**
   * XComponent id.
   */
  static readonly XCOMPONENT_ID: string = 'xcomponentId';

  /**
   * XComponent id.
   */
  static readonly XCOMPONENT_ID_2: string = 'xcomponentId2';

  /**
   * XComponent id.
   */
  static readonly XCOMPONENT_ID_3: string = 'xcomponentId3';

  /**
   * XComponent type.
   */
  static readonly XCOMPONENT_TYPE: string = 'surface';

  /**
   * XComponent library name.
   */
  static readonly XCOMPONENT_LIBRARY_NAME: string = 'wrapper';

}