# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NERtcSample-1to1-iOS-Swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NERtcSample-1to1-iOS-Swift
  pod 'NERtcSDK', '3.5.2'

  target 'NERtcSample-1to1-iOS-SwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
