# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NERtcSample-GroupVideoCall-iOS-Swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'NERtcSDK', '4.3.0'

  # Pods for NERtcSample-GroupVideoCall-iOS-Swift

  target 'NERtcSample-GroupVideoCall-iOS-SwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
