# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NERTC1to1Sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'NERtcSDK', '3.7.0'

end
