name: Basic Video Call - Android 
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  build_group_video_java:
    name: Build Group Video - Java
    runs-on: macos-latest
    env:
      APP_KEY_FILE_PATH: ${{ './app/src/main/res/values/app_key.xml' }}
      WRITE_APP_KEY_SCRIPT_PATH: ${{ '../../Shared Files/Android/write_app_key.py' }}
      ENCRYPTED_KEYSTORE_PATH: ${{ '../../Shared Files/Android/release.jks.gpg' }}
      DECRYPTED_KEYSTORE_PATH: ${{ './release.jks' }}
      UNSIGNED_APK_PATH: ${{ './app/build/outputs/apk/release/app-release-unsigned.apk' }}
      SIGNED_APK_PATH: ${{ './app/build/outputs/apk/release/GroupVideoCall-Java.apk' }}
      APP_KEY: ${{ secrets.APP_KEY }}
      KEYSTORE_ENC_PWD: ${{ secrets.KEYSTORE_ENC_PWD }}
    defaults:
      run:
        shell: bash
        working-directory: ./Group-Video/NERtcSample-GroupVideoCall-Android-Java/

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
          python-version: '3.x'

    - name: Write App Key
      run:
        python "$WRITE_APP_KEY_SCRIPT_PATH" "$APP_KEY_FILE_PATH" $APP_KEY

    - name: Configure Keystore
      run:
        gpg -d -o "$DECRYPTED_KEYSTORE_PATH" --pinentry-mode=loopback --passphrase "$KEYSTORE_ENC_PWD" "$ENCRYPTED_KEYSTORE_PATH"

    - name: Build APK
      run:
        ./gradlew assembleRelease

    - name: Sign APK
      run:
        $HOME/Library/Android/sdk/build-tools/29.0.3/apksigner sign --ks "$DECRYPTED_KEYSTORE_PATH" --ks-pass pass:$KEYSTORE_ENC_PWD --key-pass pass:$KEYSTORE_ENC_PWD --v1-signing-enabled true --v2-signing-enabled true --in "$UNSIGNED_APK_PATH" --out "$SIGNED_APK_PATH"

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: GroupVideoCall-Java
        path: ./Group-Video/NERtcSample-GroupVideoCall-Android-Java/app/build/outputs/apk/release/GroupVideoCall-Java.apk