name: Basic Video Call CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_android_java:
    name: Build Android(Java) APK
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
        working-directory: ./One-to-One-Video/NERtcSample-1to1-Android-Java

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
      
    - name: Build debug APK
      run: ./gradlew assembleDebug --stacktrace
        
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: NERtcSample-1to1-Android-Java
        path: ./One-to-One-Video/NERtcSample-1to1-Android-Java/app/build/outputs/apk/debug/app-debug.apk

  build_ios_objc:
    name: Build iOS(Objective-C)
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
        working-directory: ./One-to-One-Video/NERtcSample-1to1-iOS-Objective-C

    steps:
    - uses: actions/checkout@v2

    - name: Install Cocoapods
      run: gem install cocoapods
